import { createAPIClient } from '@shopware/api-client'

// You can pick types of your current API version, the default one:
import type { operations } from '@shopware/api-client/api-types'
// or - RECOMMENDED - your types generated by [@shopware/api-gen](https://www.npmjs.com/package/@shopware/api-gen) CLI:
// import type { operations } from "./api-types/storeApiTypes";

const runtimeConfig = useRuntimeConfig()

export const shopwareApiClient = createAPIClient<operations>({
    baseURL: runtimeConfig.public.shopware.endpoint,
    accessToken: runtimeConfig.public.shopware.accessToken,
})
